### ISSUE TITLE
Troubles with Bower install?

### ISSUE THREAD

**Issue by contentJones** [atomicpages/skeleton-sass#14]
Hello.

I'm working to get skeleton-sass installed on a yeoman webapp.

Running `bower install skeleton-sass` gives me the following:

    bower skeleton-sass#~2.0.3      cached git://github.com/atomicpages/skeleton-sass.git#2.0.3
    bower skeleton-sass#~2.0.3    validate 2.0.3 against git://github.com/atomicpages/skeleton-sass.git#~2.0.3
    bower skeleton-sass#~2.0.3     install skeleton-sass#2.0.3

    skeleton-sass#2.0.3 bower_components/skeleton-sass

But nothing is being updated in the bower.json, gruntfile.js, or main.scss. Is that typical?

**Comment by atomicpages** [comment]
I'll try to set up a test environment to see if I can duplicate the issue.

**Comment by atomicpages** [comment]
@contentJones, are you building your own generator or using a pre-packaged one? If the latter is true, which generator are you using?

**Comment by contentJones** [comment]
Thanks for checking this! I'm using generator-webapp. I did not select the libsass option

I had similar issue with generator-angular.

**Comment by atomicpages** [comment]
@contentJones, I'll check this out tomorrow afternoon and get back to you.

**Comment by contentJones** [comment]
The files are installing in the bower_components directory just fine. I was expecting the css to get inserted into all the right places, which would require a setup script of some sort. not sure if it's through Grunt or Bower... Might be a Grunt thing. Cheers!

**Comment by atomicpages** [comment]
@contentJones, just an update: I'll fix the version problem with the next release and I'll be adding a style sheet so other programs don't complain!
