### ISSUE TITLE
@import "../../_demo.config.scss";

### ISSUE THREAD

**Issue by seshaljain** [atomicpages/skeleton-sass#22]
The `skeleton\core\_config.scss` has a mention of  `@import "../../_demo.config.scss";` on line 53, but there is no  _demo.config.scss after or prior to the setup.

**Comment by atomicpages** [comment]
Great eye! Fixed!

**Comment by edanchenkov** [comment]
This bug still persists in current npm version.

**Comment by atomicpages** [comment]
@edanchenkov it looks like `npm i skeleton-sass` installs a different version of Skeleton Sass. I'll see what I can do to fix this

**Comment by edanchenkov** [comment]
@atomicpages There is something you might want to do: 1) Update Readme.md with `npm i https://github.com/atomicpages/skeleton-sass`  or 2) Publish fixed version to npm

**Comment by atomicpages** [comment]
Asking the author of the fork to change the name. Progress can be tracked here: https://github.com/menthena/skeleton-sass/pull/1

**Comment by atomicpages** [comment]
Install via:

~~~bash
npm install skeleton-sass-official --save-dev
~~~
