### ISSUE TITLE
Unable to offset columns if layout is set to fluid

### ISSUE THREAD

**Issue by pcbulai** [atomicpages/skeleton-sass#24]
https://github.com/atomicpages/skeleton-sass/blob/master/skeleton/core/_dependencies.scss#L28

I would much rather do `&:first-child:not([class^="offset"]) { margin-left: 0; }` instead, because offsetting a column is necessary regardless of the layout style( fluid or fixed ).

**Comment by atomicpages** [comment]
@pcbulai I agree.

**Comment by atomicpages** [comment]
@pcbulai I finally got around to merging in your changes in the master branch. Thank you!
