### ISSUE TITLE
First column jumps left on small screen size, .container: width gets overwritten

### ISSUE THREAD

**Issue by dirkolbrich** [atomicpages/skeleton-sass#26]
I think this is a result of a fix to #24.

Following html.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>sample title</title>

    <!-- Smartphone stuff -->
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="default" />

    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" charset="utf-8" href="/fonts/fonts.css" />
    <link rel="stylesheet" href="/css/main.css">
</head>

<body>
    <!-- .container is main centered wrapper -->
    <div class="container">
        <div class="row">
            <div class="twelve columns">
                <p>jump</p>
            </div>
        </div>
    </div>
</body>

</html>
```

On resizing the browser window and the size is between min-width: 550px and max-width: 767px, the
`<div class="twelve  #columns">` jumps to the left. At that size it has a `margin-left: 0` instead of a `margin-left: 2%`.

I could trace this bug down to `skeleton/core/_dependencies.scss:34`. If I comment this line out, the jumping stops.

**Comment by dirkolbrich** [comment]
Can be reproduced on the skeleton demo site too.

**Comment by atomicpages** [comment]
@dirkolbrich Do you have a fix that solves your issue as well as #24? I won't have time to look into this issue for a few days :(

**Comment by dirkolbrich** [comment]
Sorry, not really. I am new to .sass (1st personal project), or even css, and don't really understand the implications of changing that specific function.
Commenting that line out works for me, as I don't need to offset a column for now.

I will try some tests later on.

**Comment by dirkolbrich** [comment]
Found a starting point.
The surrounding `.container` should always have a `margin-left`and `margin-right`, on smaller screens too. Right now is goes to `width: 100%` without margins. That collides with the inner `.columns:first-child: margin-left: 0`.

The value `.container: width: 85%` for the media query at `grid.scss:21`gets somehow overwritten.

**Comment by atomicpages** [comment]
`.container` becomes overridden due to cascading. A general principle when using media queries is let the content dictate the breakpoints. A nice explanation can be found here: http://stackoverflow.com/a/36114937/1545556

At any rate, I'll look into this issue soon!

**Comment by atomicpages** [comment]
I looked into this issue and it's the same behavior of [`skeleton.css`](https://github.com/dhg/Skeleton). Demo can be found here: https://codepen.io/anon/pen/gWWpoy

To fix this behavior, I recommend creating a new theme with this fix
