### ISSUE TITLE
Theming with button colors

### ISSUE THREAD

**Issue by e-compton** [atomicpages/skeleton-sass#34]
https://github.com/atomicpages/skeleton-sass/blob/2981dcfb915153a2cad7951c4454c6abc329d853/skeleton/themes/fresh/components/_buttons.scss#L25-L41

Hi, 

I was just creating a new project with skeleton and was hoping to customize the button colors, but I noticed that they're not exposed through variables.

Could these colors be moved to variables so that users have greater control over the colors of their buttons?

thanks

**Comment by atomicpages** [comment]
@e-compton I'll see if I can get to this change over the weekend. Feel free to fork if you made the change!

**Comment by e-compton** [comment]
Sure I'll make the changes if you want. Should be able to get it done by the end of the day if you haven't already started.
